### ISSUE TITLE
Upgrade CF CLI to v7

### ISSUE THREAD

**Issue by robdimsdale** [cloudfoundry/buildpacks-github-config#3] opened 2021-10-04 19:15 UTC
Upgrade CF CLI to v7 now that CF CLI v6 is deprecated.

**Comment by johnnyr0x** [comment] 2023-02-17 16:35
Duplicate of https://github.com/orgs/cloudfoundry/projects/37/views/1?pane=issue&itemId=17705415. Can close

**Closed** 2023-02-17 16:35 UTC

**Comment by robdimsdale** [comment] 2023-02-21 14:52
FYI @johnnyr0x I didn't view them as duplicate issues because we would need to do the work in both this repo and in the `buildpacks-ci` repo. So I filed issues in both places it would need to be implemented.

But, given we closed the other one as low-priority technical debt, I think it's fine to keep this one closed too.
